### ISSUE TITLE
Org usage addition

### ISSUE THREAD

**Issue by mvpzone** [pacphi/cf-app-inventory-report#11]
As a platform operator I would like to have a view of the space managers to org in a report so I can understand the top users of the platform by organization (when mashed up with org chart).

Org, space, Space managers REST URL triggers

Other roll ups on this can identify the top org/space users

**Comment by pacphi** [comment]
I have captured org/space user details in this commit 
https://github.com/pacphi/cf-app-inventory-report/commit/9b35348bffed51f235af6eb74edd70708c2d7b24.  

Aggregate reporting (e.g., top 5 largest orgs, users with >10 or more org/space associations) is left as an exercise.
