### ISSUE TITLE
cf push has typo in its name for get-app-details-task

### ISSUE THREAD

**Issue by in4sometech** [pacphi/cf-app-inventory-report#6]
As per README

cf push get-app-details-task --no-route --health-check-type none -p ./build/libs/cf-app-inventory-report-0.0.1-SNAPSHOT.jar -m 1G --no-start

The above should be

cf push get-app-details-task --no-route --health-check-type none -p ./build/libs/**cf-app-inventory-report-0.1-SNAPSHOT.jar** -m 1G --no-start

**Comment by pacphi** [comment]
Fixed w/. https://github.com/pacphi/cf-app-inventory-report/commit/de728409f7af2bd2b0c1b38f03c9841c19619fe0
